### ISSUE TITLE
Link visibility in posts

### ISSUE THREAD

**Issue by vinnymac** [wpioneer/gatsby-starter-lumen#18]
### Summary
I noticed that anchor tags in posts had pretty much all styling stripped. I added the below styling to the anchors in posts so that they would become visible. Was this styling intentional? Seeing as the other links for the pages and read full posts are very obvious I assumed this was a bug.

For an example look at the wikipedia link on the [demo site here](http://wpioneer.github.io/gatsby-starter-lumen/my-second-post/).

If this isn't a bug, I apologize for creating more noise.

### Potential Fix
```css
.blog-single .text a:active, a:hover {
	outline: 0;
}
.blog-single .text a:active {
	color: #6a5dff;
}
.blog-single .text a:hover {
	border-bottom: 1px solid;
	color: #427ef7;
}
```

### Example of Fix
<img width="643" alt="screen shot 2016-11-23 at 4 57 41 pm" src="https://cloud.githubusercontent.com/assets/1832781/20580028/0dd3080c-b19e-11e6-89d0-14878f36d781.png">

### Additional
Currently anchors also replace the current page because they don't use `target='_blank'`. If you would like it I can easily add this behavior to lumen so it happens automatically for links in posts.
